name: Sync & Build AdbAutoPlayer

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"  # toutes les 6 heures

jobs:
  sync-and-build:
    runs-on: windows-latest  # Changé pour Windows (nécessaire pour build .exe)
    
    steps:
      # 1. Vérifier le code du fork
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # 2. Synchroniser avec le repo original
      - name: Sync with upstream
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/AdbAutoPlayer/AdbAutoPlayer.git
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit
          git push origin main
        continue-on-error: true
      
      # 3. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      # 4. Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      # 5. Builder l'executable
      - name: Build Windows executable
        run: |
          pyinstaller --noconfirm --onefile --windowed `
            --name "AdbAutoPlayer" `
            --add-data "assets;assets" `
            --add-data "config;config" `
            --icon="assets/icon.ico" `
            main.py
        continue-on-error: true
      
      # 6. Vérifier que l'exe a été créé
      - name: Check build output
        run: |
          if (Test-Path "dist/AdbAutoPlayer.exe") {
            Write-Host "✅ Build successful!"
            Get-ChildItem dist
          } else {
            Write-Host "❌ Build failed - no exe found"
            exit 1
          }
      
      # 7. Upload l'exe comme artifact
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: AdbAutoPlayer-Windows-exe
          path: dist/AdbAutoPlayer.exe
          if-no-files-found: error
      
      # 8. (Optionnel) Créer une release automatique sur tag
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/AdbAutoPlayer.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}